services:
  - type: web
    name: leadzo-goibibo-scraper
    env: node
    region: singapore
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: HEADLESS
        value: "true"
